"""Simple calculation of binned information-theoretic quantities."""

from .core import (
    calccmi,
    calccmi_slice,
    calccondcmi,
    calcinfoperm,
    calcinfoperm_slice,
    calcinfo,
    calcinfomatched,
    calcpairwiseinfo,
    calcpairwiseinfo_slice,
    calcpmi,
    calcsmi,
    entropy,
    eqpopbin,
    mmbiascmi,
    mmbiasinfo,
    numbase2dec,
    numdec2base,
    rebin,
)
from . import fastinfo

__all__ = [
    "calccmi",
    "calccmi_slice",
    "calccondcmi",
    "calcinfoperm",
    "calcinfoperm_slice",
    "calcinfo",
    "calcinfomatched",
    "calcpairwiseinfo",
    "calcpairwiseinfo_slice",
    "calcpmi",
    "calcsmi",
    "entropy",
    "eqpopbin",
    "fastinfo",
    "mmbiascmi",
    "mmbiasinfo",
    "numbase2dec",
    "numdec2base",
    "rebin",
]
